# Author: Martin Kováčik
# 
# Docker compose file for this thesis.

services:
  lissy-martin-prediction:
    container_name: lissy-martin-prediction
    build: .
    networks:
      - lissy-network
networks:
  lissy-network:
    name: lissy-network
    external: true
